# Generated by Django 4.1 on 2024-03-07 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Submit",
        ),
    ]
