# Generated by Django 4.1 on 2024-03-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submit", "0002_delete_submit"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_classification", models.CharField(max_length=20)),
                ("model_choice", models.TextField()),
                ("train_batch_size", models.FloatField()),
                ("missing_mechanism", models.CharField(max_length=20)),
                ("missing_rate", models.FloatField()),
                ("auto_parameters", models.BooleanField(default=False)),
            ],
        ),
    ]
