# Generated by Django 4.1 on 2024-03-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0002_impdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainresult",
            name="time",
            field=models.CharField(max_length=20),
        ),
    ]
