# Generated by Django 4.1 on 2024-03-29 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0003_alter_trainresult_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainresult",
            name="time",
        ),
    ]
