# Generated by Django 4.1 on 2024-03-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("time", models.TextField()),
                ("rmes", models.FloatField()),
                ("mae", models.FloatField()),
                ("accuracy", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="trainparameters",
            name="missing_mechanism",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="trainparameters",
            name="model_classification",
            field=models.CharField(max_length=10),
        ),
    ]
