# Generated by Django 4.1 on 2024-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0004_trainresult_alter_trainparameters_missing_mechanism_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainresult",
            name="time",
            field=models.TimeField(),
        ),
    ]
