# Generated by Django 4.1 on 2024-03-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0005_alter_trainresult_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impute_model", models.CharField(max_length=10)),
                ("predict_model", models.CharField(max_length=10)),
                ("perdict_batch_size", models.FloatField()),
            ],
        ),
    ]
